core/core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('managers.urls', namespace='managers')),
    path('admin/', admin.site.urls),
]

core/managers/urls.py
from django.urls import path

from managers.views import HomeView, EmployeeListView, EmployeeEditView, EmployeeDeleteView

app_name = 'managers'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('employee_list/', EmployeeListView.as_view(), name='list'),
    path('edit/<int:id>', EmployeeEditView.as_view(), name='edit'),
    path('delete/<int:id>', EmployeeDeleteView.as_view(), name='delete'),
]

core/managers/models.py
from django.db import models

optional = {
    'null': True,
    'blank': True,
}


class Position(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return(f"{self.title}")


class Employee(models.Model):
    fullname = models.CharField(max_length=200)
    emp_code = models.CharField(max_length=200)
    mobile = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE)

    def __str__(self):
        return (f"{self.fullname}")

core/managers/forms.py
from django import forms
from crispy_forms.helper import FormHelper

from managers.models import Employee


class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ('fullname', 'mobile', 'emp_code', 'position',)
        labels = {
            'fullname': 'Full name',
            'emp_code': 'Emp.code',
        }

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        self.fields['position'].empty_label = "SELECT"

core/managers/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import FormView, TemplateView, View

from managers.forms import EmployeeForm
from managers.models import Employee


class HomeView(TemplateView):
    ''' Views for home
    '''
    template_name = 'home.html'

    def get_context_data(self, *args, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        form = EmployeeForm()
        context["form"] = form
        return context

    def post(self, *args, **kwargs):
        form = EmployeeForm(self.request.POST)
        if form.is_valid():
            form.save()
            return redirect('managers:list')
        context = {
            'form': form,
        }
        return render(self.request, self.template_name, context)

class EmployeeEditView(TemplateView):
    ''' Views for editing/updating employee
    '''
    template_name = 'home.html'

    def get_context_data(self, *args, **kwargs):
        context = super(EmployeeEditView, self).get_context_data(**kwargs)
        employees = Employee.objects.get(id=kwargs['id'])
        form = EmployeeForm(instance=employees)
        context = {
            'employees': employees,
            'form': form
        }
        return context

    def post(self, *args, **kwargs):
        employees = Employee.objects.get(id=kwargs['id'])
        form = EmployeeForm(self.request.POST, instance=employees)
        if form.is_valid():
            form.save()
            return redirect('managers:list')
        return redirect('managers:edit', id=kwargs['id'])


class EmployeeListView(TemplateView):
    ''' Views for list of Employees
    '''
    template_name = 'employee_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(EmployeeListView, self).get_context_data(**kwargs)
        context["employee_list"] = Employee.objects.all().order_by('-date_created')
        return context


class EmployeeDeleteView(View):

    def post(self, *args, **kwargs):
        # em = Employee.objects.get(id=kwargs['id'])
        em = get_object_or_404(Employee, pk=kwargs['id'])
        em.delete()
        return redirect('managers:list')

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
    />
    <title>Manages</title>
  </head>
  <body>
    <div class="container">
      <div class="col-md-10 offset-md-1 mt-5">
        <div class="jumbotron">
          <h1 class="display-4">Employee Managers</h1>
          <p class="lead font-italic">
            Python django implementing CRUD Application
          </p>
          <hr class="my-4" />
          {% block content %} {% endblock %}
        </div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

core/templates/employee_list.html
{% extends "base.html" %} 

{% block content %}
<div class="container">
  <table class="table table-borderless">
    <thead class="border bottom font-weight-bold">
      <tr>
        <td>Full Name</td>
        <td>Mobile</td>
        <td>Position</td>
        <td>
          <a href="{% url 'managers:home' %}" class="btn btn-success">
            <i class="fas fa-plus"> Add Employee</i>
          </a>
        </td>
      </tr>
    </thead>
    <tbody>
      {% for employee in employee_list %}
        <tr>
          <td>
            {{ employee.fullname }}
          </td>
          <td>
            {{ employee.mobile }}
          </td>
          <td>
            {{ employee.position }}
          </td>
          <td>
            <a href="{% url 'managers:edit' employee.id %}">
              <i class="far fa-edit fa-sm"></i>
            </a>
            <form action="{% url 'managers:delete' employee.id %}" method="POST" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn">
                <i class="far fa-trash-alt fa-sm text-danger float-right"></i>
              </button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

core/templates/home.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container">
  <form method="POST" autocomplete="off">
    {% csrf_token %}
    {{ form.fullname | as_crispy_field }}
    {{ form.mobile | as_crispy_field }}
    <div class="row">
      <div class="col-md-4">
        {{ form.emp_code | as_crispy_field }}
      </div>
      <div class="col-md-8">
        {{ form.position | as_crispy_field }}
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        <button type="submit" class="btn btn-success btn-block btn-lg">
          <i class="fas fa-database"></i>
          Submit
        </button>
      </div>
      <div class="col-md-4">
        <a href="{% url 'managers:list' %}" class="btn btn-secondary btn-block btn-lg">
          <i class="fas fa-strea"></i>
          Employees list
        </a>
      </div>
    </div>
  </form>
</div>
{% endblock %}